In [1]:
# NumPy Examples - Comprehensive Guide
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


# NumPy Examples

This notebook demonstrates various NumPy operations including:
1. Array creation and basic operations
2. Array indexing and slicing
3. Mathematical operations
4. Statistical functions
5. Array reshaping and manipulation
6. Linear algebra operations

In [2]:
# 1. Array Creation Examples
print("=== Array Creation ===")

# Create arrays from lists
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array:", arr1)
print("2D array:\n", arr2)
print("Array shapes:", arr1.shape, arr2.shape)
print("Array dtypes:", arr1.dtype, arr2.dtype)

=== Array Creation ===
1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Array shapes: (5,) (2, 3)
Array dtypes: int64 int64


In [3]:
# Special array creation functions
print("=== Special Array Creation ===")

# Zeros, ones, and empty arrays
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
empty = np.empty((2, 2))

print("Zeros array:\n", zeros)
print("\nOnes array:\n", ones)
print("\nEmpty array:\n", empty)

# Range arrays
arange_arr = np.arange(0, 10, 2)  # start, stop, step
linspace_arr = np.linspace(0, 1, 5)  # start, stop, num_points

print("\nArange (0 to 10, step 2):", arange_arr)
print("Linspace (0 to 1, 5 points):", linspace_arr)

=== Special Array Creation ===
Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Empty array:
 [[1.24473916e-313 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

Arange (0 to 10, step 2): [0 2 4 6 8]
Linspace (0 to 1, 5 points): [0.   0.25 0.5  0.75 1.  ]
